version: '3'
services:
  astrometry:
    image: "astrometry/develop"
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./index/:/usr/local/astrometry/data
