version: '3'
services:
  astrometry:
    image: "astrometry"
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ${ASTROMETRY_INDEX_DATA}:/usr/local/astrometry/data
      - ${ASTROMETRY_INPUT_DATA}:/mnt
